events {}

http {
  server {
    listen 80;
    server_name localhost;

    location /api/health {
      default_type application/json;
      return 200 '{"status":"ok","entry":"nginx"}';
    }

    location /api/products {
      rewrite ^/api/products(.*)$ /products$1 break;
      proxy_pass http://product-service:3002;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/orders {
      rewrite ^/api/orders(.*)$ /orders$1 break;
      proxy_pass http://order-service:3003;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/kitchen {
      rewrite ^/api/kitchen(.*)$ /kitchen$1 break;
      proxy_pass http://kitchen-service:3004;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/notifications {
      rewrite ^/api/notifications(.*)$ /notifications$1 break;
      proxy_pass http://notification-service:3005;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
      proxy_pass http://frontend:80;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}