# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy till server
        uses: appleboy/ssh-action@v1
        with:
          host: 217.160.56.248
          username: jen
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/examination4
            git pull
            docker compose up -d --build
